### ISSUE TITLE
Task k8s controller variable

### ISSUE THREAD

**Issue by TheAceMan** [bjw-s-labs/home-ops#7748]
Having issues getting task to determine values using:

https://github.com/bjw-s-labs/home-ops/blob/83fde9d17505edeb55855f264fa1fd71231b2716/.taskfiles/k8s-bootstrap/Taskfile.yaml#L10

sh in the var section does not have the same variables or environment values available and getting errors. Believe this is related to https://www.github.com/go-task/task/issues/1742, curious if this is working for you or if there is a work around for this.

**Comment by bjw-s** [comment]
I'm not really able to reproduce an issue:

```sh
…/home-ops > talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
10.1.1.31
```

Everything seems to be working for me?

**Comment by TheAceMan** [comment]
The statement itself runs fine. The issue is when it is ran in the task var section. Within the sh it does not have access to the env variables like TALOSCONFIG and the statement fails within the task. I added these tasks to my taskfile and see the output below:

```
tasks:
  tal:
    cmds:
      - talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1

  talcontroller:
    cmds:
      - echo $TALOSCONFIG
      - echo $TALOS_CONTROLLER
      - echo {{.TALOS_CONTROLLER}}
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
```

The tal task runs succssfully:
```
$ task tal
task: [tal] talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
192.168.40.40
```

However talcontroller has a error _no context is set_ because it does not have access to the variables when running talosctl.
```
$ task talcontroller
no context is set
task: [talcontroller] echo $TALOSCONFIG
/home-ops/kubernetes/cluster-0/talos/clusterconfig/talosconfig
task: [talcontroller] echo $TALOS_CONTROLLER

task: [talcontroller] echo

```

Do you have default shell env values set that maybe are used in this scenario? Or maybe it's because I am using WSL on Windows? Might be something you would not notice with one cluster but I am switching between two clusters.
